# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-18 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['~user__updated', '~user__timestamp']},
        ),
    ]
