# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-17 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurantlocation_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='owners',
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
