# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-17 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_auto_20180617_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='owners',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
