# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-17 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20180617_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='owners',
        ),
    ]
